config/routes.rb
Rails.application.routes.draw do
  get "/users/auth/:provider/callback" =>'top#callback'
  devise_for :users
  root 'top#index'
  get 'top' => 'top#index'
  get 'search' => 'top#search'
  get 'review/:id' => 'top#entry'
  post 'review/:lesson_id' => 'top#post'
  resources :lessons 
  resources :reviews

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
  end

  def show
    @positive = 0
    @negative = 0
    @sum = 0
    @reviews = Review.where(lesson_id: params[:id]).page(params[:page]).order("id,'DESC'").per(10)
    @lesson= Lesson.find(params[:id])
    @reviews.each do |review|
      @sum += 1 
      if review.emotion == "P"
        @positive += 1
      else
        @negative += 1
      end
      @pp =@positive*100.0/@sum
      @np =@negative*100.0/@sum
    end
    @average=Review.average(:rate,:conditions => ["lesson_id = #{params[:id]}"]).round
# binding.pry
  end

  def create
    # params[]http://mueki.net/twana/api.php
    require 'net/http'
    require 'uri'
    #POSTするだけ
    res = Net::HTTP.post_form(URI.parse('http://mueki.net/twana/api.php'),
                          {'q'=>params[:review], 'max'=>'50'})
    # puts res.body
    if params[:nickname].empty? then
      params[:nickname] = "名無し"
    end
    @review = Review.new(nickname: params[:nickname],rate: params[:rate], review: params[:review], lesson_id: params[:lesson_id],emotion: res.body)
    if @review.save then
      redirect_to "/reviews/#{params[:lesson_id]}"
    else
      redirect_to "/review/#{params[:lesson_id]}?alert=1"
    end
      
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for @review, :html => { :class => "form-horizontal review" } do |f| %>

    <% if @review.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :nickname, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nickname, :class => 'form-control' %>
    </div>
    <%= error_span(@review[:nickname]) %>
  </div>
  <div class="control-group">
    <%= f.label :rate, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :rate, :class => 'form-control' %>
    </div>
    <%= error_span(@review[:rate]) %>
  </div>
  <div class="control-group">
    <%= f.label :review, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :review, :class => 'form-control' %>
    </div>
    <%= error_span(@review[:review]) %>
  </div>
  <div class="control-group">
    <%= f.label :lesson_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :lesson_id, :class => 'form-control' %>
    </div>
    <%= error_span(@review[:lesson_id]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            reviews_path, :class => 'btn btn-default' %>

<% end %>

app/views/reviews/edit.html.erb
<%- model_class = Review -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/reviews/index.html.erb
<%- model_class = Review -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nickname) %></th>
      <th><%= model_class.human_attribute_name(:rate) %></th>
      <th><%= model_class.human_attribute_name(:review) %></th>
      <th><%= model_class.human_attribute_name(:lesson_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= link_to review.id, review_path(review) %></td>
        <td><%= review.nickname %></td>
        <td><%= review.rate %></td>
        <td><%= review.review %></td>
        <td><%= review.lesson_id %></td>
        <td><%=l review.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_review_path(review), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      review_path(review),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_review_path,
            :class => 'btn btn-primary' %>

app/views/reviews/new.html.erb
<%- model_class = Review -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/reviews/show.html.erb
<div class="container">
  <div style="border-bottom: 3px solid #d7dbe2;">
  <h3>
    <%= @lesson.title %>&nbsp
    <span style="color: #ab1541;">
      <span class="glyphicon glyphicon-thumbs-up"></span><%=@positive%>&nbsp&nbsp&nbsp&nbsp
    </span>
    <span class="glyphicon glyphicon-thumbs-down"></span><%=@negative%>&nbsp&nbsp&nbsp&nbsp
    <img src="http://img.realworld.jp/realpedia/img/star<%= if @average/2.round ==0 then 1 else @average/2.round end %>.0.gif" alt="">
  </h3>
  <a href="/review/<%= @lesson.id %>">レビューを書く</a>
  </div>
<!-- <input id="input-id" type="number" class="rating" min=1 max=10 step=2 data-size="lg" data-rtl="true"> -->

  
  <% if @reviews.present?  then @reviews.each do |review| %>
    <div style="border-bottom: 3px solid #d7dbe2;">
      <h4>
        <%= review.nickname %>さん
        <span class="color-sub"><img src="http://img.realworld.jp/realpedia/img/star<%= if review.rate/2.round ==0 then 1 else review.rate/2.round end %>.0.gif" alt=""></span>
      </h4>
      <span>レビュー</span>
      <h5><%= if review.emotion=="P" then "○" else  "×" end %><%= review.review %></h5>
    </div>
  <%end%>
  <div>
    <%= paginate(@reviews) %>
  </div>
    <%end%>
</div>